{% set python_min = '3.11' %}
{% set name = "virtualizarr" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virtualizarr-{{ version }}.tar.gz
  sha256: 593c79b1482aeef6b672d2c9b8621abe700af3f3880c314e01780c8f2c4dbc73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2025.1.1
    - numpy >=2.0.0
    - packaging
    - universal_pathlib
    - numcodecs
    - ujson
  run_constrained:
    - imagecodecs >=2024.6.1
    - kerchunk >=0.2.8
    - icechunk >=0.1.1

test:
  imports:
    - virtualizarr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/virtualizarr/
  summary: Create virtual Zarr stores from archival data using xarray API
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - virtualizarr/vendor/zarr/LICENSE.txt

extra:
  recipe-maintainers:
    - TomNicholas
    - maxrjones
