{% set python_min = '3.10' %}
{% set name = "virtualizarr" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virtualizarr-{{ version }}.tar.gz
  sha256: 0eb9aecf09fd347d1691b407ed3798f55f038a3044bd9ccd23bd9c49f90e036d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2024.10.0
    - numpy >=2.0.0
    - packaging
    - universal_pathlib
    - numcodecs
    - ujson

test:
  imports:
    - virtualizarr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/virtualizarr/
  summary: Create virtual Zarr stores from archival data using xarray API
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - virtualizarr/vendor/zarr/LICENSE.txt

extra:
  recipe-maintainers:
    - TomNicholas
    - maxrjones
