{% set python_min = "3.11" %}
{% set name = "virtualizarr" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virtualizarr-{{ version }}.tar.gz
  sha256: b852f35bea62892dbe20cc963ebea8cf09e357729004a4eecbca331b8d91e046

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=7.0
    - pip
  run:
    - obspec_utils >=0.7.0
    - obstore >=0.7.0
    - universal-pathlib
    - zarr >=3.1.0
    - python >={{ python_min }}
    - xarray >=2025.03.0
    - numpy >=2.0.0
    - packaging
    - numcodecs >=0.15.1
    - ujson
  run_constrained:
    - imagecodecs >=2024.6.1
    - kerchunk >=0.2.8
    - icechunk >=1.1.2

test:
  imports:
    - virtualizarr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/virtualizarr/
  summary: Create virtual Zarr stores from archival data using xarray API
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - TomNicholas
    - maxrjones
