{% set python_min = "3.11" %}
{% set name = "virtualizarr" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virtualizarr-{{ version }}.tar.gz
  sha256: 9aa1a5895ac13814cd5979c9f23490bdfa8a1d2991fa20e34f098dbd32531169

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=7.0
    - pip
  run:
    - obstore >=0.5.1
    - universal-pathlib
    - zarr >=3.1.0
    - python >={{ python_min }}
    - xarray >=2025.03.0
    - numpy >=2.0.0
    - packaging
    - universal_pathlib
    - numcodecs >=0.15.1
    - ujson
  run_constrained:
    - imagecodecs >=2024.6.1
    - kerchunk >=0.2.8
    - icechunk >=1.1.2

test:
  imports:
    - virtualizarr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/virtualizarr/
  summary: Create virtual Zarr stores from archival data using xarray API
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - TomNicholas
    - maxrjones
