{% set name = "virtualizarr" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/virtualizarr-{{ version }}.tar.gz
  sha256: 6d78d6b94e0341fe728783debfbbeb64cbca986b134ee7014885640379e6e47b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - xarray >=2024.06.0
    - kerchunk >=0.2.5
    - h5netcdf
    - pydantic
    - numpy >=2.0.0
    - ujson
    - packaging
    - universal_pathlib

test:
  imports:
    - virtualizarr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/virtualizarr/
  summary: Create virtual Zarr stores from archival data using xarray API
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - virtualizarr/vendor/zarr/LICENSE.txt

extra:
  recipe-maintainers:
    - TomNicholas
    - maxrjones
